- name: install first domain controller
  hosts: win
  gather_facts: yes
  tasks:
   - name: install ad
     win_feature: >
          name=AD-Domain-Services
          include_management_tools=yes
          include_sub_features=yes
          state=present
     register: result
   - name: install domain
     win_domain: >
        dns_domain_name='awx.local'
        safe_mode_password='SafeMode!'
     register: ad
   - name: reboot server
     win_reboot:
      msg: "Installing AD. Rebooting..."
      pre_reboot_delay: 15
     when: ad.changed
 
