---
- hosts: all
  become: true
  become_method: sudo
  tasks:

  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    
  - name: Install a yum package 
    yum:
      name: "{{ items }}"
      state: present
      with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - ansible
      - git
      - python-devel
      - python-pip
      - vim-enhanced

