---
- hosts: all
  become: true
  become_method: sudo
  tasks:

  - name: Install a yum package 
    yum:
      name: epel-release
      state: present
    
  - name: Install a yum package 
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'ansible', 'git', 'python-devel', 'python-pip', 'vim-enhanced']
      state: present
