---
- hosts: all
  become: true
  become_method: sudo
  tasks:

  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  
  - name: enable EPEL repository (some .repo file with contents [epel]
    yum_repo_enabler:
      name=epel
      enabled=True
    
  - name: Install a yum package 
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'ansible', 'git', 'python-devel', 'python-pip', 'vim-enhanced']
      state: present

