---
- hosts: all
  become: true
  become_method: sudo
  tasks:
   
  - name: Install a yum packages 
    yum:
      name: ['epel-release', 'yum-utils', 'device-mapper-persistent-data', 'lvm2', 'ansible', 'git', 'python-devel', 'python-pip', 'vim-enhanced']
      state: present

