---
- hosts: all
  become: true
  become_method: sudo
  tasks:
  
  - name: Install Public Key of EPEL 7
    command: rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

  - name: Install EPEL 
    yum:
      name: epel-release
      state: present
    
  - name: Install a yum package 
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'ansible', 'git', 'python-devel', 'python-pip', 'vim-enhanced']
      state: present
